export const siteConfig = {
  name: "Harshit Bhatia",
  title: "Harshit Bhatia | Enterprise Agentic AI CTO & Architect",
  description:
    "Harshit Bhatia, CTO at Assert AI, builds enterprise agentic AI systems across platform engineering, computer vision, edge AI and AI security.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://harshitbhatia.in",
  location: "Delhi, India",
  role: "Chief Technology Officer",
  company: "Assert AI",
  education: [
    {
      school: "Indian School of Business",
      program: "Emerging Leaders Programme, Organizational Leadership",
      period: "Jun 2024 - Jan 2025",
    },
    {
      school: "Maharaja Surajmal Institute Of Technology",
      program: "Bachelor of Technology - BTech",
      period: "Apr 2017 - May 2021",
    },
  ],
  keywords: [
    "Harshit Bhatia",
    "Harshit Bhatia CTO",
    "Harshit Bhatia Delhi",
    "Harshit Bhatia ISB",
    "Indian School of Business",
    "AI",
    "Enterprise AI",
    "Enterprise Agentic AI Systems",
    "AI Platform Engineering",
    "AI Security",
    "Computer Vision",
    "Edge AI",
    "CTO",
    "LangGraph",
    "LLMs",
    "Artificial Intelligence",
  ],
  links: {
    linkedin: "https://in.linkedin.com/in/harshitbhatiacto",
    github: "https://github.com/bhatiaharshit07",
    email: "mailto:bhatiaharshit07@gmail.com",
    resume: "/resume.pdf",
  },
};
