export const siteConfig = {
  name: "Harshit Bhatia",
  title: "Harshit Bhatia | Enterprise AI CTO & Architect",
  description:
    "Harshit Bhatia, CTO at Assert AI, builds enterprise agentic AI systems across platform engineering, computer vision, edge AI, and AI security.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://harshitbhatia.in",
  location: "Delhi, India",
  role: "Chief Technology Officer",
  company: "Assert AI",
  companyUrl: "https://www.assertai.com",
  companyTeamUrl: "https://www.assertai.com/our-team/",
  companyLinkedIn: "https://www.linkedin.com/company/assert-ai/",
  education: [
    {
      school: "Indian School of Business",
      program: "Emerging Leaders Programme, Organizational Leadership",
      period: "Jun 2024 - Jan 2025",
    },
    {
      school: "Maharaja Surajmal Institute Of Technology",
      program: "Bachelor of Technology - BTech",
      period: "Apr 2017 - May 2021",
    },
  ],
  patent: {
    title:
      "System and method for personalizing a computer vision model based on use cases",
    identifier: "US12482245B2",
    number: "US 12,482,245 B2",
    publicationNumber: "US 2025/0252720 A1",
    status: "Granted",
    granted: "25 November 2025",
    grantedIso: "2025-11-25",
    assignee: "Assert Secure Tech Pvt Ltd",
    inventors: ["Job Varughese Philip", "Harshit Bhatia", "Happy Mishra"],
    url: "https://patents.google.com/patent/US12482245B2/en",
  },
  keywords: [
    "Harshit Bhatia",
    "Harshit Bhatia CTO",
    "Harshit Bhatia Delhi",
    "Harshit Bhatia ISB",
    "Indian School of Business",
    "AI",
    "Enterprise AI",
    "Enterprise AI CTO India",
    "Enterprise Agentic AI Systems",
    "Agentic AI Architect India",
    "AI Platform Engineering",
    "AI Security",
    "Computer Vision",
    "Computer Vision CTO India",
    "Edge AI",
    "CTO",
    "Multi-Agent Systems Architect",
    "LangGraph",
    "LLMs",
    "Artificial Intelligence",
  ],
  links: {
    linkedin: "https://www.linkedin.com/in/harshitbhatiacto/",
    github: "https://github.com/bhatiaharshit07",
    email: "mailto:bhatiaharshit07@gmail.com",
    resume: "/resume.pdf",
  },
};
